### ISSUE TITLE
Question on using restcommander for more than rest

### ISSUE THREAD

**Issue by kojikeneda** [eBay/restcommander#16]
Has there been given any thought to allowing generic remote polling/execution of tests with restcommander. 

I see references in the documentation to monitoring for HTTP healthcheck page polling and aggregating those results but am wondering if anyone is using restcommander for port checks and/or other tests that are typically remotely executed. 

Thanks in advance for any info!

**Comment by kojikeneda** [comment]
Sorry, I just found the answer to my own issue. For anyone else that stops by http://www.parallec.io is the place to check it seems if you are after more generic use cases. I just didn't see it before entering this.

**Comment by jeffpeiyt** [comment]
Hi @kojikeneda , thanks for your interests in REST Commander.  Please let me know if you have more questions. Yes, parallec.io has more generic use cases but serves as a stand alone library
