### ISSUE TITLE
Empty reply from server and maxConcurrency in Dashboard for "commandToSingleTargetServer"

### ISSUE THREAD

**Issue by agustintorres** [eBay/restcommander#17]
Two issues:

Issue 1: I am using the "commandToSingleTargetServer" as follows:

```
small request:

curl -X POST --data-binary "@myfile-small.json" http://<myrestcommanderURL>/commands/commandToSingleTargetServer
{"result":"ADHOCDATASTORE_NODEGROUP_20160920082707099-0700","time":"2016.09.20.08.27.12.601-0700"}

large request:

curl -X POST --data-binary "@myfile.json" http://<myrestcommanderURL>/commands/commandToSingleTargetServer
curl: (52) Empty reply from server
```

where the only difference between the two commands is that the "small request" is for only 10 URLs while "large request" is for 20,000 URLs (all going to the same server). As you can see, the small request response is a JSON with result and time, but for the large request it is an empty response. Why is this?

Further, I'm trying to figure out a way to get at the results, even for the small request. Using the "result" in the JSON, I could get to:

`http://<myrestcommanderURL>/nodeGroups/nodeGroupType?nodeGroupType=ADHOCDATASTORE_NODEGROUP_20160920082707099-0700&isAdhoc=true`

However, the actual results are here:

`http://<myrestcommanderURL>/logs/logContent/20160920082712522-0700~ADHOCDATASTORE_NODEGROUP_20160920082707099-0700~GET_NETWORTH.jsonlog.txt`

And I cannot get to them because the "20160920082712522-0700" part of the URL is a timestamp that does not match the timestamp I get in the response (which is "2016.09.20.08.27.12.**601**-0700").

Issue 2: Even though the command has a maxConcurrency set to 4, when I look at the Dashboard, I see the "Max Concurrency" column display 500 for my task. Why is this? I can't be sure which maxConcurrency it is actually using nor where the 500 comes from.

**Comment by jeffpeiyt** [comment]
hi @agustintorres , thanks for trying out REST Commander.

Current implementation does not support async job calling. You will have to wait for the response to come back. We decided to implement the async job with progress tracking in [Parallec.io](http://www.parallec.io/) with many other improvements and flexibility:  check [example](https://github.com/eBay/parallec-samples/blob/master/sample-apps/src/main/java/io/parallec/sample/app/http/HttpBasicAsyncRunProgressPollingApp.java)

The maxConcurrency should work for the commands.    the first 0 after the /act/index.rss is the concurrency (default as 1500)  ,  could you please try this and modified the 1st 0 and see if it works?  http://www.restcommander.com/documentation.html#Commands

thanks,

```
GET_CRAIGSLIST_RSS GET http 80 /act/index.rss 0 0 5000 SUPERMAN_GLOBAL
```$AM_FULL_CONTENT 
```

**Comment by agustintorres** [comment]
@jeffpeiyt Thanks for the prompt reply. I actually do not want async job calling. I'm happy waiting for the response as long as it's needed. My question was why for the second curl request, I get "(52) Empty reply from server". Do you think this is most likely an issue on my end, and restcommander itself should return a response once it's done, even if it takes 10 minutes?

For maxConcurrency, this is my command:

GET_NETWORTH GET http 80 /networth/$UID 4 -1 -1 SUPERMAN_GLOBAL
```$AM_FULL_CONTENT

As you can see, the maxConcurrency is set to 4. However, when I look at the task for that command in the Dashboard, maxConcurrency display as 500 (see below). I have no idea where that 500 could be coming from.

![screen shot 2016-09-20 at 2 45 58 pm](https://cloud.githubusercontent.com/assets/11450276/18684113/038eea62-7f41-11e6-8263-d39a8f240228.png)

**Comment by jeffpeiyt** [comment]
hi @agustintorres , I just realize that probably you did not use the master branch (master branch did not have the dashboard and many features in distributed manner); but use the distributed version branch:  as the default concurrency is set at 500: check [here](https://github.com/eBay/restcommander/blob/distributed_commander/AgentMaster/conf/application.conf)

Could you please try the master branch, it has less feature but I just tested the concurrency changes is working in display.  

The distributed version was not completed tested in production and we suggest you use the master branch version for reliability.

**Comment by agustintorres** [comment]
@jeffpeiyt: Thanks for the insight. I gave Parallec a try and decided it fits my use case better, so I will be using it for now. Feel free to close this issue.

**Comment by jeffpeiyt** [comment]
Thank you @agustintorres ! Please feel free to raise issues in parallec if you have more questions.
