### ISSUE TITLE
Oops: ClassFormatException

### ISSUE THREAD

**Issue by BustedSec** [eBay/restcommander#18]
When running the windows .bat file on a fresh clone if the repo, I get the following output in the webserver 
Oops: ClassFormatException 

An unexpected error occured caused by exception ClassFormatException:
null 

This exception has been logged with id 71ld1n7eo 

and the following output from the program:

C:\restcommander>start_application_win.bat

---

Go to your browser for http://localhost:9000 to run the program.
Close this window to exit the program and please run
clean_application_pid_after_run_win.bat

---

The system cannot find the file specified.
~        _            _
~  _ __ | | __ _ _  _| |
~ | '_ | |/ _' | || |_|
~ |  **/|_|__**|__ (_)
~ |_|            |__/
~
~ play! 1.2.4, http://www.playframework.org
~
~ OK, C:\restcommander\AgentMaster is started
~ output is redirected to C:\restcommander\AgentMaster\logs\system.out
~ pid is 11228
~
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; sup
port was removed in 8.0

**Comment by jeffpeiyt** [comment]
@thatrez thanks for trying rest commander.

Seems this issue is very similar to https://groups.google.com/forum/#!topic/rest-commander-users/VEZY5NdBtIA  with the JAVA HOME / and incompatibility issue with JDK 8 on play 1.2.x. 

Could you please check this out and see if you can get it resolved?
